server:
  port: 0

spring:
  application:
    name: collector
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

grpc:
  server:
    port: 0

kafka:
  topics:
    user-actions: stats.user-actions.v1

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/
  instance:
    preferIpAddress: true
    instance-id: "${spring.application.name}:${random.value}"
