server:
  port: 0

spring:
  application:
    name: aggregator
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: stats-aggregator
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

kafka:
  topics:
    user-actions: stats.user-actions.v1
    event-similarity: stats.events-similarity.v1

recommendations:
  action-weights:
    view: 1.0
    register: 2.0
    like: 3.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/
  instance:
    preferIpAddress: true
    instance-id: "${spring.application.name}:${random.value}"
