server:
  port: 0

spring:
  application:
    name: analyzer
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Europe/Moscow
        show_sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6541/statistics
    username: statistics
    password: statistics
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: stats-analyzer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer

grpc:
  server:
    port: 0

kafka:
  topics:
    user-actions: stats.user-actions.v1
    event-similarity: stats.events-similarity.v1

recommendations:
  neighbors-count: 5
  action-weights:
    view: 0.4
    register: 0.8
    like: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/
  instance:
    preferIpAddress: true
    instance-id: "${spring.application.name}:${random.value}"
